### ISSUE TITLE
404 for casing of HTML file names in the docs

### ISSUE THREAD

**Issue by eyedean** [tamtamchik/apple-iap-tools#7]
Thanks for helping us save some time with this package! <3 @tamtamchik 

Just so you know, link in the side bar of https://tamtamchika.net/apple-iap-tools/modules.html for `ServerNotificationResponseBody` goes to https://tamtamchika.net/apple-iap-tools/interfaces/ServerNotificationResponseBody.html which is a 404.
The correct one seems to be  https://tamtamchika.net/apple-iap-tools/interfaces/servernotificationresponsebody.html which is entirely-lowercase version of that.

It's the same situation for most of them.

Thanks!

**Comment by tamtamchik** [comment]
Thanks for pointing it out. Upgrading `typedoc` to the latest version and re-adding files to the git repo fixed it.

**Comment by eyedean** [comment]
Thanks!
